services:
  lizardfs-client:
    image: mwaeckerlin/lizardfs-client:mrw-privat
    build: .
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
